#! /usr/bin/env bash

cwd="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -e $cwd/.git ] ; then

  # Check for git on the system
  git=`which git`

  if [ "$git" = "" ] ; then
    echo "ERROR! You must have git installed to use this script!!!"
    exit
  fi

  branch=`git rev-parse --abbrev-ref HEAD`

  if [[ $branch =~ "devel" ]]; then
    echo `git describe`
  else
    dots=`echo $branch | grep -o "\." | wc -l`

    case $dots in

      0|1)
        echo "$branch.0"
      ;;

      2)
        echo $branch
      ;;

    esac
  fi
else
  cat $cwd/.version
fi
