#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(cd "$(dirname "$0")"; pwd)")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

if [ -z "${CMAKE_PREFIX_PATH}" ] ; then
  echo "You must set CMAKE_PREFIX_PATH in your environment"
  exit 1
fi

#------------------------------------------------------------------------------#
# Check command-line arguments
#------------------------------------------------------------------------------#

cmake_mode=cmake
extra_define=""
runtime=mpi
kokkos=OFF

while [[ $# -gt 0 ]]
do

	case $1 in
		--help|-h)
			command=`echo $0 | sed 's,.*\/,,g'`
			echo "Usage: $command [options] runtime"
			echo "  -h, --help     Show this message and exit."
			echo "  -c, --ccmake   Enable curses mode."
			echo ""
			echo "Runtimes: legion, mpi."
			echo "(default runtime is mpi)."
			exit
      shift #past argument
		;;
		--ccmake|-c)
			cmake_mode=ccmake
      shift #past argument
		;;
    legion|hpx)
      runtime=$1
      shift #past argument
    ;;
    kokkos)
      kokkos=ON
      shift #past argument
    ;;
	esac

done

if [ $runtime = legion ]; then clog=OFF
else clog=ON; fi

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

$cmake_mode \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_CXX_FLAGS="-fmax-errors=5 -Wno-deprecated-declarations" \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_C_FLAGS="-fmax-errors=5" \
  -DFLECSI_RUNTIME_MODEL=$runtime $extra_define \
  -DENABLE_BOOST=ON \
  -DENABLE_CLOG=$CLOG \
  -DCLOG_ENABLE_TAGS=$CLOG \
  -DENABLE_DEVEL_TARGETS=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DENABLE_FLECSIT=ON \
  -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
  -DENABLE_KOKKOS=$kokkos \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  $cinch_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
