#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(cd "$(dirname "$0")"; pwd)")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

if [ -z "${CMAKE_PREFIX_PATH}" ] ; then
  echo "You must set CMAKE_PREFIX_PATH in your environment"
  exit 1
fi

#------------------------------------------------------------------------------#
# Check command-line arguments
#------------------------------------------------------------------------------#

cmake_mode=cmake
runtime=mpi
cmake_args=""

while [[ $# -gt 0 ]]
do

	case $1 in
		--help|-h)
			command=`echo $0 | sed 's,.*\/,,g'`
			echo "Usage: $command [options] runtime"
			echo "  -h, --help     Show this message and exit."
			echo "  -c, --ccmake   Enable curses mode."
			echo ""
			echo "Runtimes: legion, mpi."
			echo "(default runtime is mpi)."
			exit
		;;
		--ccmake|-c)
			cmake_mode=ccmake
		;;
    legion|hpx)
      runtime=$1
    ;;
    *)
      cmake_args="$cmake_args $1"
    ;;
	esac

	shift # next argument
done

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

echo "Executing:"
echo "$cmake_mode -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS=\"-fmax-errors=5 -fdiagnostics-color=always\" -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS=\"-fmax-errors=5 -fdiagnostics-color=always\" -DFLECSI_RUNTIME_MODEL=$runtime -DENABLE_FLOG=ON -DENABLE_UNIT_TESTS=ON -DENABLE_FLECSIT=ON -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} $cmake_args $cinch_dir"
echo ""

$cmake_mode \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_CXX_FLAGS="-fmax-errors=5 -fdiagnostics-color=always" \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_C_FLAGS="-fmax-errors=5 -fdiagnostics-color=always" \
  -DFLECSI_RUNTIME_MODEL=$runtime \
  -DENABLE_FLOG=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DENABLE_FLECSIT=ON \
  -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
  $cmake_args \
  $cinch_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
