#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(cd "$(dirname "$0")"; pwd)")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

if [ -z "${CMAKE_PREFIX_PATH}" ] ; then
  echo "You must set CMAKE_PREFIX_PATH in your environment"
  exit 1
fi

#------------------------------------------------------------------------------#
# Check runtime
#------------------------------------------------------------------------------#

if [ -z "$1" ] ; then
	runtime=serial
else
	runtime=$1

	case $1 in
		legion)
		;;
		mpilegion)
			extra_define="-DENABLE_MPI=ON"
		;;
	esac
fi

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

cmake \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_CXX_FLAGS="-fmax-errors=5 -pedantic -Wall -Werror" \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_C_FLAGS="-fmax-errors=5 -pedantic -Wall -Werror" \
  -DFLECSI_RUNTIME_MODEL=$runtime $extra_define \
  -DENABLE_UNIT_TESTS=ON \
  -DENABLE_JENKINS_OUTPUT=ON \
  -DENABLE_EXODUS=ON \
  -DENABLE_PARTITION=ON \
  -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
  $cinch_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
